apiVersion: v1
kind: Service
metadata:
  name: transfer-service-assessment
spec:
  type: LoadBalancer
  selector:
    app: transfer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080